### ISSUE TITLE
Typo in namespace

### ISSUE THREAD

**Issue by dejagersh** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#22]
`MigrationsMutlipleDatabase`

`Mutlipe`

**Comment by devnix** [comment]
I'm no longer giving updates to this project. It has some quirks that I never got the time to fix, and there are no tests guaranteeing compatibility with all "supported" Symfony versions or that something is broken.

I strongly suggest several alternatives:
- Try to achieve the same functionality with a makefile, [here is a practical example](https://github.com/AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle/discussions/21)
- **Put your energies into pushing this functionality into the core project, rather than into an unmaintained package**
- Fork this repository and maintain your package
- Also, ask yourself: do you _really_ need different databases? Like _really really_?

I'm archiving the project here in GitHub and abandoning it on Packagist.
