### ISSUE TITLE
Problem when using liip monitoring bundle

### ISSUE THREAD

**Issue by xammmue** [AvaiBookSports/DoctrineMigrationsMultipleDatabaseBundle#6]
It seems to like there is a problem when using this bundle and liip monitoring bundle in combination.

When running the liip monitoring for doctrine migrations, no migrations are found in the directory (because no migration directory is passed to Doctrine\Migrations\Configuration\Configuration.
This results in the following check failure because more migrations are marked as executed in the database than found in the directories
`Doctrine migrations "migrations_with_doctrine_bundle": Migrations applied which are not available`

Did anyone encounter this or a similar problem already and know of a possible solution?

**Comment by devnix** [comment]
Hi @xammmue! Never worked with LiipMonitorBundle, but would you mind sharing your LiipMonitorBundle 
 and DoctrineMigrationsMultipleDatabaseBundle configurations?

**Comment by xammmue** [comment]
Hi, thanks for the fast reply

monitor.yaml (liipMonitorBundle)
`
liip_monitor:
    enable_controller: true
    checks:
        php_extensions: [amqp, redis, ctype, curl, iconv, json, pdo]
        php_version:
            version: '>='
            7.2.0: '>='
        doctrine_dbal: default
        doctrine_migrations:
            migrations_with_doctrine_bundle:
                connection:          default
        doctrine_mongodb:        default
        redis:
            name:
                host:       '%env(REDISDB_HOST)%'
                port:       '%env(int:REDISDB_PORT)%'
                password:   '%env(REDISDB_PASSWORD)%'
        rabbit_mq:
            rabbitmq_default:
                host:       '%env(RABBITMQ_HOST)%'
                port:       '%env(int:RABBITMQ_PORT)%'
                user:       '%env(RABBITMQ_USER)%'
                password:   '%env(RABBITMQ_PASSWORD)%'
                vhost:      '%env(RABBITMQ_VHOST)%'
`

`
doctrine_migrations_multiple_database:
    entity_managers:
        default:
            migrations_paths:
                'DoctrineMigrations': '%kernel.project_dir%/migrations'
        datasource:
            migrations_paths:
                'DoctrineMigrationsDatasource': '%kernel.project_dir%/migrations_datasource'

`

**Comment by devnix** [comment]
I guess it's missing a default configuration for DoctrineMigrationsBundle. I'm supposing LiipMonitorBundle parses DoctrineMigrationsBundle config files to get info like the entity manager or the migrations path, and this bundle uses its own configuration file and overrides DoctrineMigrationsBundle commands.

You could configure your DoctrineMigrationsBundle to the default migrations folder but you would check only one database migrations. If it doesn't work for you, I highly suggest you ask on LiipMonitorBundle's repository, because it is more related to their internals rather than our internals. You can link this issue too and I'll be happy to answer any doubts from them, but **take in consideration this disclaimer**:

Symfony states the following in their documentation:
>Using multiple entity managers is not complicated to configure, but more advanced and not usually required. Be sure you actually need multiple entity managers before adding in this layer of complexity.

>Entities cannot define associations across different entity managers. If you need that, there are [several alternatives](https://stackoverflow.com/questions/11463517/using-relationships-with-multiple-entity-managers/11494543#11494543) that require some custom setup.

https://symfony.com/doc/current/doctrine/multiple_entity_managers.html

And we claim to solve some problems "in a hacky and dirty way", to solve a very specific need usually in legacy scenarios.

If you are doing a new application, I would strongly suggest you to use one database and one migrations folder if there is not a **very** good reason to have this splitted. If you still want to go to the multiple database solution, beware the dragons 😄 

Feel free to reopen the issue if you feel I'm missing something 👍🏻

**Comment by xammmue** [comment]
The missing configuration actually was the problem. When I added DoctrineMigrationsMultipleDatabaseBundle, I also removed that configuration as I thought having that stuff duplicated would lead to problems. Adding the configuration back solved the issue.
Thank you!

Short explanation of the decision for multiple database just in case anyone is curious:
My software is running in a microservice environment. Because there is sort of a main configuration spread across multiple tables which is needed in almost all services synchronization was they chosen way until now. But this leads to a massive amount of synchronization messages being sent around. The other 2 options were either queries to the service responsible for that configuration or directly reading from that services database with a read only user. So we don't need the additional set of migrations here.
When running integration tests though, we need to have that other database also available. But as only a single service is tested, we need to create both database schemas (the tested service and foreign service) to be created. Which is where we need that second set of migrtaions.
